---
title: "Welling_Project_Code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Simulate data for project code:
```{r}
set.seed(40)
x1 <- runif(40, min = 20, max = 34)
epsilon <- rnorm(40, mean = 0, sd = 1)
y <- x1^2 + epsilon

plot(y ~ x1)
```


#Models for the thermal performance curve:
This first approach will fit built in models and a few custom built models, and the
library will calculate AIC values. 

```{r}
#install thermal performance curve package
library(devtools)
install_github("mdjbru-R-packages/thermPerf")
```

```{r}
#call library
library(thermPerf)

# Plot the raw data
plot(x1, y, pch = 21, bg = "grey")
```


```{r}
#fit the models in the library to the data
fits = fitModels(getModelLibrary(), x1, y)
plot(fits)
```

```{r}
#calculate AIC values for the models
weights = calculateAIC(fits)
plot(weights)

weights
```


```{r}
#Creating a model for the quadratic function
#1) Function
mFunction = function(x, params) {
# params model parameters, a, b, c
    a = params[["a"]]
    b = params[["b"]]
    c = params[["c"]]
    return(a * x^2 + b * x + c)
}

#2) Name
mName = "Quadratic"

#3) Formula
mFormula = y ~ a * x^2 + b * x + c

# 4) Model parameters
mParams = c("a", "b", "c")

# 5) List of starting values for the parameters
mStarting = list(a = 1, b = 1, c = 1)

# Create the customModel object
Quadratic = buildModel(mFunction, mName, mFormula, mParams, mStarting)

# Summary
Quadratic
```



```{r}
#Creating a model for the Gaussian function
#1) Function
mFunction = function(x, params) {
# params model parameters, a, b, c
    a = params[["a"]]
    b = params[["b"]]
    c = params[["c"]]
    return( a * (exp( ((-0.5) * ((abs(x - b)) / c )^2))) )
}

#2) Name
mName = "myGaussian"

#3) Formula
mFormula = y ~ a * (exp( ((-0.5) * ((abs(x - b)) / c )^2)))

# 4) Model parameters
mParams = c("a", "b", "c")

# 5) List of starting values for the parameters
mStarting = list(a = 1, b = 1, c = 1)

# Create the customModel object
myGaussian = buildModel(mFunction, mName, mFormula, mParams, mStarting)

# Summary
myGaussian
```


```{r}
#Fit Custom models

#Fit the model, along with the best one from the original model library
models = getModelLibrary()[c("candidate04")]
models[["Quadratic"]] = Quadratic
models[["myGaussian"]] = myGaussian
fits2 = fitModels(models, x1, y)
plot(fits2)

#Get AIC values
weights2 = calculateAIC(fits2)
weights2
plot(weights2)

```
```{r}

```



#Maximum Likelihood Approaches
Using maximum likelihood approaches, we can get another model-fit test. 

```{r}
#Building a max likelihood approach for a linear model

Linear_max <- function(p, X, Y) {
  b0 <- p[1]; b1 <- p[2]; sd <- p[3]
  
  rsd <- (b0 + b1*X ) - Y
  
  -sum(dnorm(rsd, mean = 0, sd = sd, log = T)) 
}

linear_optim <- optim(c(1, 0, 5), Linear_max, X = x1, Y = y)
linear_optim
```

```{r}
#Max likelihood for quadratic

Quadratic_max <- function(p, X, Y) {
  a <- p[1]; b <- p[2]; c <- p[3]
  
  rsd2 <- (a*(X^2) + b*X + c) - Y
  
  -sum(dexp(rsd2, rate = X/Y, log = T))
}

quadratic_optim <- optim(c(1, 1, 1), Quadratic_max, X = x1, Y = y)
quadratic_optim
```

```{r}
#Maximum likelihood for Gaussian

Gaussian_max <- function(p, X, Y) {
  a <- p[1]; b <- p[2]; c <- p[3]; sd <- p[4]
  
  rsd3 <- a * (exp( ((-0.5) * ((abs(X - b)) / c )^2))) - Y
  
  -sum(dnorm(rsd3, mean = 0, sd = sd, log = T)) 
}

gaussian_optim <- optim(c(0, 0, 0, 1), Gaussian_max, X = x1, Y = y)
gaussian_optim
```
```{r}
#Maximum Likelihood for modified Gaussian

modGaussian_max <- function(p, X, Y) {
  a <- p[1]; b <- p[2]; c <- p[3]; d <- p[4]; sd <- p[5]
  
  rsd4 <- a * (exp( ((-0.5) * ((abs(X - b)) / c )^d))) - Y
  
  -sum(dnorm(rsd4, mean = 0, sd = sd, log = T)) 
}

gaussian_optim <- optim(c(0, 0, 0, 2, 1), modGaussian_max, X = x1, Y = y)
gaussian_optim
```
```{r}
#Maximum Likelihood for Weibull 


```

